# Generated by Django 4.2.1 on 2023-08-02 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('amount_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone_number', models.CharField(max_length=255)),
                ('payment_method', models.CharField(choices=[('mpesa', 'Mpesa'), ('cash', 'Cash'), ('credit', 'Credit')], max_length=255)),
                ('mpesa_data', models.JSONField(default=dict)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
