# Generated by Django 4.2.1 on 2023-08-03 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderpayment',
            old_name='amount_payment',
            new_name='amount_paid',
        ),
    ]
